---
jupyter:
  jupytext:
    formats: ipynb,Rmd,R:light
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.16.4
  kernelspec:
    display_name: R
    language: R
    name: ir
---

#find edges that are consistently higher than 0

```{r}
library('I2C2') 
library('tidyverse') 
```


```{r}
icc_calc <- function(df) { 

df$pos <- NULL
    
wide_df <- pivot_wider(data=df, names_from='X', values_from='values')
    
y <- wide_df[-1:-2]
id <- wide_df$sub
visit <- wide_df$ses

i2c2_res <- I2C2(y, id = id, visit = visit, demean = TRUE) 
i2c2_ci <- I2C2.mcCI(y, id = id, visit = visit, demean = TRUE)$CI

icc_obj = list(i2c2_res, i2c2_ci)

return(icc_obj) 
 } 
```

### MSMAll

```{r}
results_path = '/global/homes/m/mphagen/functional-connectivity/connectome-comparison/results/MSMAll'

lasso_df = read.csv(file.path(results_path, 'lasso_icc_df.csv')) 
lasso_icc <- icc_calc(lasso_df)
lasso_icc[[1]]$lambda
lasso_icc[[2]]

pearson_df = read.csv(file.path(results_path, 'pearson_icc_df.csv')) 
pearson_icc <- icc_calc(pearson_df) 
pearson_icc[[1]]$lambda
pearson_icc[[2]]
```

#### XCPD

```{r}
results_path = '/global/homes/m/mphagen/functional-connectivity/connectome-comparison/results/xcpd'

lasso_df = read.csv(file.path(results_path, 'lasso_icc_df.csv')) 
lasso_icc <- icc_calc(lasso_df)
lasso_icc[[1]]$lambda
lasso_icc[[2]]

pearson_df = read.csv(file.path(results_path, 'pearson_icc_df.csv')) 
pearson_icc <- icc_calc(pearson_df) 
pearson_icc[[1]]$lambda
pearson_icc[[2]]
```